### ISSUE TITLE
Табы на странице сущности

### ISSUE THREAD

**Issue by vlad-pokusa** [mindbox-moscow/ui-kit#1048]
- Выпиливаем логику, по которой если мы находимся на странице сущности и переходим по меню куда-то еще, то отовсюду можно вернуться к навигации по табам сущности по кнопке "назад" (не весь код из предыдущего тикета, там должны были починиться табы в меню)

Логика работы:
Находимся на странице сущности - в заголовок меню пробрасывается часть хлебных крошек, добавляется кнопка "Назад", ведущая на предыдущий уровень меню
Пример - страница клиента, кампании

<img width="1291" alt="Снимок экрана 2020-06-23 в 19 01 38" src="https://user-images.githubusercontent.com/57757197/85427663-b67a4b80-b584-11ea-8cbd-ebd543133a35.png">
<img width="1141" alt="Снимок экрана 2020-06-23 в 18 57 46" src="https://user-images.githubusercontent.com/57757197/85427671-ba0dd280-b584-11ea-8950-12d7ed8d36a8.png">

При переходе к уровню, из которого можно сделать переход к открытой сейчас сущности любым способом, показываем стрелку вправо, которая ведет в навигацию по табам сущности.

<img width="791" alt="Снимок экрана 2020-06-23 в 19 03 48" src="https://user-images.githubusercontent.com/57757197/85428401-d1998b00-b585-11ea-9c36-9633d20851a3.png">

Тест кейсы: 
- находимся в сущности, нажали в меню "Назад", открылся 2 уровень, появилась стрелка "Вперед", ведет к навигации по табам сущности
- находимся в сущности, нажали текущий корневой раздел меню, открылся 2 уровень, появилась стрелка "Вперед", ведет к навигации по табам сущности
- находимся в сущности "Профиль клиента", нажали "Интеграции" - Настройки рассылок, передумали, нажали "Данные", сразу вернулись к навигации по табам Профиля клиента. Есть кнопка "Назад", ведет в меню 2 уровня.

**Comment by timramone** [comment]
- [ ] Добавить опциональный props в меню, который позволяет переопределить название текущего пункта меню в шапке
