### ISSUE TITLE
Кнопка "наверх" не сбрасывается

### ISSUE THREAD

**Issue by Shabanovv** [mindbox-moscow/ui-kit#1058]
https://recordit.co/O5F1hCF9on

Пропал фильтр по каналам. Есть только кнопка "наверх" http://joxi.ru/eAOXj0QUpBNBpr

Воспроизводится на ноутбуке - разрешение 1440х900

Форс реалоад не помогает. Воспроизводится на боевом проекте https://charuel.mindbox.ru/channels

**Comment by vlad-pokusa** [comment]
Это чинит Тема Сахацкий если что https://mindbox.slack.com/archives/CS4K0L01H/p1592906161013200
