### ISSUE TITLE
Ссылка на акцию/группу

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#197]

**Comment by itsyrulnikov** [comment]
При нажатии на три точки. 
![image](https://user-images.githubusercontent.com/21079693/69634796-0f701880-1064-11ea-8dd1-4b767f12d7e8.png)
отображается пункт "Скопировать ссылку на акцию" или "Скопировать ссылку на групппу" ( в зависиммости от типа элемента).
При этом в буфер обмена копируется ссылка.

При переходе по ссылке раскрывается связанная акция/группа и страничка скролится к ней.
