### ISSUE TITLE
Визуализация успешного/неудачного сохранения дерева

### ISSUE THREAD

**Issue by d-i-bondarenko** [mindbox-moscow/ui-kit#260]
Необходима отображать пользователю результат сохранения дерева.
Если все успешно, то внизу показываем желтенькую плашку "Изменения сохранены" без кнопки "Отменить".
Если неуспешно, то отображаем внизу такую же плашку, но с красным бэкграундом. На ней отображаем "При сохранении возникли ошибки". 
Красный цвет должен быть похож на наш старый, но тут лучше попробовать и посмотреть как будет выглядеть

![image](https://user-images.githubusercontent.com/21079693/66143176-641c8780-e60f-11e9-851c-603e7ea28c08.png)

И в списке перечисляем ошибки.

**Comment by itsyrulnikov** [comment]
> Вроде всё понятно. Пара-тройка вопросов:
> - Какой таймаут для скрытия плашки?
> - Клик за пределами плашки скрывает плашку?
> - Удержание мышки над плашкой, сбрасывает таймаут скрития плашки? (edited) 

1. Давай поставим пока 5 секунд, докрутим на практие
2. Нет, я бы лучше явно крестик сделал в правом верхнем углу. Реально?
3. Да
