### ISSUE TITLE
Собрать примеры фильтров

### ISSUE THREAD

**Issue by sitnikovanastya** [mindbox-moscow/ui-kit#265]
Мини-репорт по созвону:
1. Делаем все примеры со страницы (Сценарий 1, Сценарий 2) https://projects.invisionapp.com/share/PVTFFQ44T6Y#/screens/379709794
2. 2 и 5 из этих мокапов: https://projects.invisionapp.com/share/PVTFFQ44T6Y#/screens/378955726_19_-_Or___And_Groups

Ссылку скинуть со всеми примерами в чат по фильтрам в Слаке

**Comment by CubiZm** [comment]
http://feature-issue-265.mindbox.csssr.ru/#filtrationgroupcomponent
