### ISSUE TITLE
Валидация изменения стейта акции

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#278]
Возможна ситуация, когда в группе с правилом, нпример, **последовательное применение** лежит акция с **округлением** и стейтом **в разработке** при этом в **possibleStates** у неё есть **запустить**. У этой группы можно изменить правило применения на **суммирование**, оно меняется без проблем, потому что указанная акция игнорируется при валидации, так как у неё стейт **в разработке**. Таким образом, теперь есть группа с правилом применения **суммирование** и акция в ней с **округлением** и стейтом **в разработке** и возможным стейтом **запущена**. Получается при попытке смена стейта акции нужно валидировать на фронте такую смену, в данном случае не смотря на то, что в **possibleStates** есть **Execution**, нужно запретить его выбор, иначе ветка будет невалидной.

**Comment by d-i-bondarenko** [comment]
Других вариантов, где потребуется валидация поверх `possibleStates` не нашёл.
