### ISSUE TITLE
Драг-н-дроп только внутри группы

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#286]

**Comment by itsyrulnikov** [comment]
При драг и дропе должны учитываться стандартные правила валидации:
 - сначала скидки
 - потом округление
 - потом начисление баллов

Соответственно, когда скидочную акцию переносят в группу, в которой уже есть округления и балльные акции, то эта скидочная акция должна становится последней скидочной акцией.
Аналогично с округлением (последней акцией с округлением) и начислением баллов.
