### ISSUE TITLE
Валидация перемещения внутри группы

### ISSUE THREAD

**Issue by itsyrulnikov** [mindbox-moscow/ui-kit#300]
Если переместить акцию или группы в другую группу через перемещение дерева, то акцию/группа не всегда должна становиться в конец как сейчас.

Должны учитывать стандартные правила валидации:
 - сначала скидки
 - потом округление
 - потом начисление баллов

Соответственно, когда скидочную акцию переносят в группу, в которой уже есть округления и балльные акции, то эта скидочная акция должна становится последней скидочной акцией. 
Аналогично с округлением (последней акцией с округлением) и начислением баллов.

**Comment by itsyrulnikov** [comment]
Новая скидочная акция встает сюда на тесте: https://yadi.sk/i/6aGnNr8SWmh3nQ
Видимо это связано с тем, что валидация учитывает заархивированные акции, хотя не должна.

**Comment by buzorin** [comment]
Похоже не учитывается стейт отдкльных акций (не групп), который должен игнорироваться — в разработке и заархивирована.
