### ISSUE TITLE
Вывод элементов при фильтрации

### ISSUE THREAD

**Issue by itsyrulnikov** [mindbox-moscow/ui-kit#308]
Для быстрого поиска по названию ветки, подходящие под фильтрации отображаем как в мокапе https://projects.invisionapp.com/share/XESA7T1ZJ2B#/screens/374814789

Хлебные крошки, которые не подходят под фильтр по названию, затемняем. 

Если в хлебных крошка есть акции, которые подходят под фильтр по названию, то они остаются незатеменными (как сейчас). 

Если в названии хлебных крошек встречается подходит под фильтр по названию, то подходящая часть выделяется жирным.

**Comment by buzorin** [comment]
Разбил на две задачи #426 и #427
