### ISSUE TITLE
Брекет в режиме редактирования обрезается контроллом фильтра

### ISSUE THREAD

**Issue by timramone** [mindbox-moscow/ui-kit#372]
https://test.staging.directcrm.ru/products/with-new-filter?filter=or%28is-available%28filter-mode%28Absent%29%29%29or%28is-available%28filter-mode%28Absent%29%29%29

Если ткнуть на брекет ИЛИ, то будет видна проблема 

![image](https://user-images.githubusercontent.com/898920/65726296-70f42500-e0bd-11e9-8ef1-5992941b6112.png)

Проблема в том же самом, что и с меню. Надо пофиксить :(

**Comment by timramone** [comment]
Валь, Вадим просто подвинул весь фильтр вправо. Соответственно слева стало больше места и это ушко влезает. Смотри сам, можешь вернуть в доедлки, сейчас хотя бы пользоваться можно. Ну или закрыть

**Comment by Shabanovv** [comment]
Кажется, что ок. Пока не вижу сценария, при котором мы хотим, чтобы этот лейбл вылезал за пределы блока фильтрации. 

Мб на маленьких экранах будет важно, там и обсудим
