### ISSUE TITLE
Новый вид поповера редактирования фильтра

### ISSUE THREAD

**Issue by Shabanovv** [mindbox-moscow/ui-kit#403]
![image](https://user-images.githubusercontent.com/41429186/66120090-bb583300-e5e2-11e9-8aea-e5ce79dfcdcd.png)

- Больше нет звездочки, теперь там крестик
- Заголовок сжат по вертикали
- Появилась вкладка "дублировать" (это мокап, цвет фона сделать как у блока, а цвет иконки - как у цвета кнопок "применить")

**Comment by timramone** [comment]
@Shabanovv впихни это в меню плз

**Comment by Shabanovv** [comment]
https://github.com/mindbox-moscow/ui-kit/issues/402
