### ISSUE TITLE
Удаление и дублирование фильтра по ховеру

### ISSUE THREAD

**Issue by Shabanovv** [mindbox-moscow/ui-kit#407]
![image](https://user-images.githubusercontent.com/41429186/66120168-f195b280-e5e2-11e9-9219-9abcd614776e.png)

Иконка корзинки - такая же как при удалении блока
Иконка дублировать - можем ли использовать какую-то стандартную?

**Comment by timramone** [comment]
`onConditionRemove` уже есть, нужно добавить `onConditionDuplicate`. Если этот callback null, не отображаем иконку (мы пока не делаем этот функционал)

**Comment by timramone** [comment]
Я бы тут ещё Кирилла подождал, он уже скоро это нарисует
