### ISSUE TITLE
Сохраняется не сохраненное изменение модификатора

### ISSUE THREAD

**Issue by Shabanovv** [mindbox-moscow/ui-kit#439]
Проблема: 

1. Когда редактирую условие, но при этом не сохраняю его и закрываю - при повторном редактировании выводится результат предыдущего НЕ сохраненного редактирования. Ожидание: при редактировании должно показываться то значение, которое сейчас в фильтре

![image](https://user-images.githubusercontent.com/41429186/66647842-a6a71b00-ec32-11e9-979d-223a68fc3b93.png)

2. Если сменить выбор с "заполнен и любой" на "заполнен и...", то в выпадашке пустое значение

![image](https://user-images.githubusercontent.com/41429186/66647950-f2f25b00-ec32-11e9-849d-2fa9d8c8283b.png)

Гифка - https://recordit.co/nXeXEsHyt1

**Comment by stug111** [comment]
Это скорей всего не ко мне

**Comment by timramone** [comment]
@Shabanovv это к дев2
