### ISSUE TITLE
Поместить большие контролы в новое меню

### ISSUE THREAD

**Issue by Shabanovv** [mindbox-moscow/ui-kit#457]
Проблема: попап ШД большой и непонятно, как он впихнется в новое меню

Нужно это сделать и посмотреть, что получается (мб некоторые пункты на новые строки перенести 

![image](https://user-images.githubusercontent.com/41429186/67000671-ee212180-f0e0-11e9-8ead-cef91f24106e.png)

____________

Другие контролы 

- Шаблон действия - контролы сбоку
- После действия/сумма изменений баланса/процент открытий и кликов = много больших выпадах
- Сумма оплаты по заказам продуктов = сам по себе фильтр + вложенный

**Comment by timramone** [comment]
@Shabanovv давай мы закроем это, я не понимаю, что тут делать CSSSR
