### ISSUE TITLE
Попап сложного контрола в меню

### ISSUE THREAD

**Issue by Shabanovv** [mindbox-moscow/ui-kit#503]
Фильтр "после действия" https://projects.invisionapp.com/share/C5UK3ETFKJN#/screens/390521098

При клике на "действия с шаблоном" появляется попап этого контрола https://projects.invisionapp.com/share/C5UK3ETFKJN#/screens/390521097

![image](https://user-images.githubusercontent.com/41429186/67894545-cc587d80-fb69-11e9-82c4-121c4e88f15f.png)

**Comment by timramone** [comment]
@Shabanovv у нас уже есть попап, может используем его? зачем нам новый?
