### ISSUE TITLE
Кнопка применить работает при пустом фильтре

### ISSUE THREAD

**Issue by Shabanovv** [mindbox-moscow/ui-kit#528]
Есть пустой фильтр 

![image](https://user-images.githubusercontent.com/41429186/68475900-69867680-023a-11ea-8ef4-1f0253c10550.png)

Когда перехожу в меню добавления фильтра - появляются кнопки применения/сброса, на которые я могу нажать. Хотя фильтр все еще пустой

![image](https://user-images.githubusercontent.com/41429186/68475888-6095a500-023a-11ea-9943-2de5ed2cf3a0.png)

Ожидание: если фильтр пустой, нет кнопок применить/сбросить фильтр

**Comment by timramone** [comment]
@Shabanovv ну это лучше к нам заведи, только напиши там, какое поведение ожидаешь
