### ISSUE TITLE
Убрать надпись "Без максимальной скидки"

### ISSUE THREAD

**Issue by itsyrulnikov** [mindbox-moscow/ui-kit#539]
![image](https://user-images.githubusercontent.com/21079693/68698179-68827b80-0591-11ea-9e16-e647c469f5af.png)

**Comment by buzorin** [comment]
Плюс вот это https://mindbox.slack.com/archives/CKZF99L77/p1573751726030200?thread_ts=1573747483.029500&cid=CKZF99L77
![](http://s.csssr.ru/UJVFK0SM8/20191114201315.jpg)
