### ISSUE TITLE
Вертикальные полосы наезжают на рамки группы

### ISSUE THREAD

**Issue by itsyrulnikov** [mindbox-moscow/ui-kit#583]
![image](https://user-images.githubusercontent.com/21079693/69533501-fba3b400-0f88-11ea-9321-fc6af0cb58ad.png)

**Comment by itsyrulnikov** [comment]
Че-то все равно наезжают 
![image](https://user-images.githubusercontent.com/21079693/70257944-5e245d80-179c-11ea-95be-438939ce706f.png)

**Comment by buzorin** [comment]
Вылезла другая бага https://mindbox.slack.com/archives/CKZF99L77/p1575541776046600
