### ISSUE TITLE
Разбить MapDispatchToProps на три группы (Core, View, Edit)

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#616]
Использовать тот же редьюсер и инициализвцию, что есть у компонента `SaveMailing` сейчас. Будет загружаться довольно много лишнего, легче всего будет в процессе работы над задачей удалить ненужное. Так что придётся `DirectCrm\src\Mailings\MapDispatchToProps.ts:onInitialize` разбить на методы типа `initializeMailingPageCore`, где должны остаться все инициализации, необходимые обеим страницам, а так же сделать `initializeEditMailingPage` и `initializeViewMailingPage`, которые бы вызывали сначала общую инициализацию, а потом докручивали бы остальное.

**Comment by polikashina** [comment]
[Просмотр рассылки: Разбить MapDispatchToProps на три группы (Core, View, Edit) #1407](https://github.com/mindbox-moscow/frontend/pull/1407)
