### ISSUE TITLE
Меню

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#620]
Компонент меню страницы редактирования находится тут `DirectCrm\src\Mailings\Menu\SaveMailingMenu.tsx`. 
На новой странице должно быть такое же меню, но с другими кнопками. Кнопка отображается всегда, если не указано иное.

Кнопки:
- Пауза: отображается только если идёт отправка
- Отмена: отображается, только если рассылка на паузе
- Возобновить отправку: отображается только если рассылка на паузе
- Клонировать
- История редактирования
- Удалить: отображается только если у текущего пользователя есть права на удаление

Все действия этих кнопок уже реализованы на текущей странице редактирования, нужно переиспользовать это поведение.

**Comment by polikashina** [comment]
Стилизация кнопок должна быть такой же как на странице промоакций https://test.staging.directcrm.ru/promotions/2442, ссылки с подчеркиванием нужно заменить на кнопки
