### ISSUE TITLE
Добавляем блоки с вариантами

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#652]
Все данные, которые отображаются сейчас, уже есть в стейте. Нужно просто отображать их по-другому.

На странице редактирования отросовкой вариантов занимается `DirectCrm\Mailings\src\Variant\VariantsEditor.tsx`, в котором можно указать, какие компоненты будут использоваться в зависимости от канала. Например, настройка этого компонента для email указана тут: `DirectCrm\Mailings\Email\src\EmailMailingEditor.tsx`

- [x] **Один вариант для email-рассылок**

Если вариант один, то мы рисуем длинную панель во всю ширину, разделенную на несколько частей. В правой части отрисовывается превью. 

Данные вариантов находятся в `model.variants`. У каждого варианта есть `template`, в котором должен быть `htmlFormat` и может быть `ampFormat`.

Превью для email-рассылки отрисовываем по аналогии с компонентом `EmailVariantSidebar`, но без кнопки отправки тестового сообщения. Придётся вытащить из него компонент `EmailVariantPreview`, в котором будет только превью, чтобы переиспользовать его между страницами. 

- [x] **Несколько вариантов для email-рассылок**

В случае, когда в рассылке несколько вариантов, мы должны отображать небольшие панели, нужно исправить верстку панелей так, чтобы мы могли их складывать таким образом.

**Comment by vlad-pokusa** [comment]
Сползло превью, на доступной клиентам странице тоже
<img width="1238" alt="Снимок экрана 2020-01-16 в 20 26 29" src="https://user-images.githubusercontent.com/57757197/72547860-870d3780-389e-11ea-8c5d-08dd1a64a21c.png">
В остальном все хорошо
