### ISSUE TITLE
UI таблицы

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#655]
Важно понимать следующие требования к таблице:
- Все русские названия должны браться из props'ов из-за локализации
- Колонки "целевое действие" может не быть.
- Маркер "критерий оценки" может быть установлен на любой из колонок "открыто/кликнуто/целевое действие", а может отсутствовать
- Строка "КГ" может отсутствовать
- Если вариант только 1, то будет отсутствовать строка "Все"

API компонента таблицы мне представляется примерно таким:

```
/* FancyTable */

interface ColumnDefinition {
    columnHeaderComponent: JSX.Element;
}

interface ColumnDefinitions {
    [key: string]: ColumnDefinition
}

interface FancyTableStateProps {
    columnDefinitions: ColumnDefinitions;
    columnsToShow: string[];
}

/* FancyTableRow */

interface CellDefinition {
    cellContentComponent: JSX.Element;
}

interface CellDefinitions {
    [key: string]: CellDefinition
}

interface FancyTableRowStateProps {
    cellDefinitions: CellDefinitions;
    cellsToShow: string[];
}
```

Если будет более удобен какой-то другой API, то и ладно. Очевидно, что в этом никак не учтены различия в отображении строк, видимо нужно будет добавить для этого соответствующие props'ы.

**Comment by vlad-pokusa** [comment]
<img width="669" alt="Снимок экрана 2020-01-21 в 15 13 17" src="https://user-images.githubusercontent.com/57757197/72804041-9c98ad80-3c60-11ea-971e-cb3164f80be7.png">

**Comment by timramone** [comment]
Тут на созвоне договорились, что сделаем второй метод `getShortCurrency`, который будет возвращать не полное наименование валюты, а символ доллара, рубля и т.п.
