### ISSUE TITLE
Меню доп. ссылок по вариантам

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#656]
Переносим в UI-Kit со страницы акций. Плюс отрисовываем это меню в двух вариантах: в виде меню с поповером, если места мало, и в виде просто списка ссылок, если места хватает. Было бы здорово, если бы компонент сам так делал на ризиновом мокапе, но не уверен, что это реалистично без лагов сделать.

**Comment by vlad-pokusa** [comment]
В фигме вариант для не-емейлов с 1 вариантом выглядит так: 

<img width="977" alt="Снимок экрана 2020-02-25 в 20 49 18" src="https://user-images.githubusercontent.com/57757197/75274248-91aedb00-5813-11ea-8fc2-86e82643a50f.png">

У нас сейчас там огромный отступ под кнопку (которой не бывает в рассылке только с 1 вариантом и без контрольной группы) 
https://test.staging.directcrm.ru/campaigns/4738/mailings/5202/view

<img width="1292" alt="Снимок экрана 2020-02-25 в 21 13 48" src="https://user-images.githubusercontent.com/57757197/75274387-d63a7680-5813-11ea-8571-8965960e2550.png">

Нужно, чтобы для рассылок с 1 вариантом без кг этого отступа не было, и таблица растягивалась на это белое пространство.

На странице емейл рассылки для рассылки только с 1 вариантом без кг три точки тоже должны быть максимально справа (выделить три точки в отдельный от кнопки блок, чтобы они не выезжали на середину пустого блока?)

<img width="1248" alt="Снимок экрана 2020-02-25 в 21 18 41" src="https://user-images.githubusercontent.com/57757197/75274765-785a5e80-5814-11ea-89b6-cfa6609cad49.png">

**Comment by buzorin** [comment]
Завёл отдельную задачу на это — #804

> В фигме вариант для не-емейлов с 1 вариантом выглядит так:
> 
> <img alt="Снимок экрана 2020-02-25 в 20 49 18" width="977" src="https://user-images.githubusercontent.com/57757197/75274248-91aedb00-5813-11ea-8fc2-86e82643a50f.png">
> 
> У нас сейчас там огромный отступ под кнопку (которой не бывает в рассылке только с 1 вариантом и без контрольной группы)
> https://test.staging.directcrm.ru/campaigns/4738/mailings/5202/view
> 
> <img alt="Снимок экрана 2020-02-25 в 21 13 48" width="1292" src="https://user-images.githubusercontent.com/57757197/75274387-d63a7680-5813-11ea-8571-8965960e2550.png">
> 
> Нужно, чтобы для рассылок с 1 вариантом без кг этого отступа не было, и таблица растягивалась на это белое пространство.
> 
> На странице емейл рассылки для рассылки только с 1 вариантом без кг три точки тоже должны быть максимально справа (выделить три точки в отдельный от кнопки блок, чтобы они не выезжали на середину пустого блока?)
> 
> <img alt="Снимок экрана 2020-02-25 в 21 18 41" width="1248" src="https://user-images.githubusercontent.com/57757197/75274765-785a5e80-5814-11ea-89b6-cfa6609cad49.png">
