### ISSUE TITLE
Используем таблицу на странице

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#657]
При инициализации страницы нужно подтягивать данные статистики. Для запроса статистики нужно делать 3 запроса, они разделены по тяжести запросов. Делаем редьюсер и экшны для сохранения данных статистики. Предусматриваем, что данные из этих запросов могут придти в любом порядке. Не забываем написать на это тесты.

Первый запрос возвращает данные быстро, и там будут основные данные для статистики: 
- метаданные самой рассылки: критерий оценки (выбранный алгоритм)
- по каждому варианту: участия, отправки, открытия, клики, отписки, состояние варианта

Второй -- более тяжелые для подсчета данные: по каждому варианту выручка, средний чек, конверсия в заказ и количество заказов.

Третий -- по каждому варианту целевое действие, если оно есть

Мы должны отображать таблицу только когда выполнился первый запрос. В ячейках, для которых данные ещё не загрузились, рисуем прелоадеры. Когда данные по второму запросу загрузились, отрисовываем и их.

**Comment by vlad-pokusa** [comment]
- Поправить как считается средний чек: Выручка / Количество заказов. Сейчас сумма в 100 раз больше, чем надо.
- Добавить десятые к показателю доставленных, открытых, кликнутых (к процентам).
- Добавить сотые к показателю отписок и конверсии в заказ

<img width="1249" alt="Снимок экрана 2020-02-03 в 17 39 31" src="https://user-images.githubusercontent.com/57757197/73662203-71747c00-46ac-11ea-864e-6843757eb5f4.png">

**Comment by gradiusalisik** [comment]
http://s.csssr.ru/U0EJNN8RL/2020-02-04-14-07-04-eiy8y.jpg

**Comment by gradiusalisik** [comment]
Необходимо http://s.csssr.ru/U0EJNN8RL/2020-02-05-16-36-20-2xR3r.jpg
