### ISSUE TITLE
Фильтр по датам на странице

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#659]
Храним текущий выбранный фильтр по датам в сторе. Соответственно, делаем редьюсер и экшны для этого. При изначальной загрузке страницы должен быть выбран период за всё время.

При изменении фильтра перезапрашиваем данные таблицы. Для этого пишем сагу, подписанную на изменение периода, она запрашивает данные для таблицы сама, знает все моменты, когда их нужно запросить. У нас уже есть примеры саг в фильтрах, так что проблем возникнуть не должно. Важно корректно обработать отмену саги (когда мы выбрали фильтр, подождали, у нас ничего не загрузилось и мы выбираем другой фильтр). На это должны быть написаны тесты.

**Comment by vlad-pokusa** [comment]
Фильтр по датам должен быть виден только в триггерных рассылках.

**Comment by vlad-pokusa** [comment]
На статусе договорились что нужно:
- Выпилить из интерфейса задание точного времени, оставить даты
- При изменении ренджа дат делать таблицу прозрачной + прелоадер
- Контрол должен быть только в триггерных рассылках, в ручных - нет.
