### ISSUE TITLE
Варианты рассылок: Поддержка остальных каналов

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#664]
Кроме email у нас поддерживаются рассылки по другим каналам. Для каждого канала варианты отображаются по-своему, и нужно это учесть. 
Для отображения контролла редактирования вариантов на странице редактирования рассылки используется `DirectCrm\src\Mailings\Components\MailingEditorWrapper.tsx`. Он обращается к `MailingConfiguration.getContainerComponent`, чтобы понять, какой компонент отрисовывать в зависимости от канала. 
Наше отображение вариантов в зависимости от канала нужно сделать точно так же. Метод `getContainerComponent` нужно переименовать в `getEditContainerComponent`, и сделать `getViewContainerComponent`, который будет возвращать компонент просмотра вариантов для страницы просмотра. После этого нужно найти все реализации `MailingModelConfigurationBase` (для email, sms, viber и др. каналов) и указать корректный для них компонент просмотра варианта.

**Comment by vlad-pokusa** [comment]
Viber: 

- При вводе длинного текста сжимается и разваливается превью телефона. Если добавить url кнопки, разваливается, но по-другому.
- Сейчас по клику на знак "Цепочки" рядом со ссылкой происходит переход. Нужно заменить на копирование ссылки в буфер обмена.
- Добавить поле "текст кнопки" и сам текст кнопки, по аналогии с урлом перехода по кнопке

Все варианты как что-то сломать можно посмотреть в рассылке и на скриншоте:

https://test.staging.directcrm.ru/campaigns/3906/mailings/3564/view

<img width="1243" alt="Снимок экрана 2020-01-16 в 19 51 09" src="https://user-images.githubusercontent.com/57757197/72545128-9047d580-3899-11ea-8eb2-a982adb43bb4.png">

**Comment by vlad-pokusa** [comment]
Смс:
В Фигме видно текст сообщения, в верстке - не видно
<img width="1089" alt="Снимок экрана 2020-01-16 в 19 00 08" src="https://user-images.githubusercontent.com/57757197/72546430-d140e980-389b-11ea-9913-c5b6ddbff35d.png">
<img width="1237" alt="Снимок экрана 2020-01-16 в 19 00 17" src="https://user-images.githubusercontent.com/57757197/72546440-d3a34380-389b-11ea-8ef3-9b981fb5f264.png">

**Comment by vlad-pokusa** [comment]
Вебпуш:

- Текст вебпуша не переносится на новую строку
- При переключении с хрома на хром мобайл изменяется ширина блока превью
- Превью не соответствует оригиналу и сильно искажается
- https://test.staging.directcrm.ru/campaigns/3906/mailings/4333/view

<img width="1243" alt="Снимок экрана 2020-01-16 в 20 16 04" src="https://user-images.githubusercontent.com/57757197/72547145-1c0f3100-389d-11ea-9292-e085f3ac6a1b.png">

**Comment by vlad-pokusa** [comment]
Мобильный пуш

В фигме влезает

<img width="804" alt="Снимок экрана 2020-01-16 в 20 21 01" src="https://user-images.githubusercontent.com/57757197/72547461-c25b3680-389d-11ea-8712-467477703047.png">

В верстке не влез
<img width="1220" alt="Снимок экрана 2020-01-16 в 20 21 41" src="https://user-images.githubusercontent.com/57757197/72547530-df900500-389d-11ea-991c-7f175143a994.png">

**Comment by vlad-pokusa** [comment]
Нужно выпилить текст "Варианты рассылки"

**Comment by vlad-pokusa** [comment]
Вебпуш - ок
Viber - ок
Мобильный пуш - нужно телефон в полную высоту как в Viber, не видно текст и картинку
Смс - нужно телефон в полную высоту как в Viber, не видно текст и картинку
