### ISSUE TITLE
When - Set actions. Нет дат под кнопкой

### ISSUE THREAD

**Issue by juliyalozovaya** [mindbox-moscow/ui-kit#67]
http://mindbox.csssr.ru/When/ Блоки 2, 4, 5, 6, 7. Нет дат под кнопкой "Триггер активен на протяжении всей кампании" http://s.csssr.ru/UE886ASBY/20181215_18.07.51.jpg http://s.csssr.ru/UE886ASBY/20181215_18.08.17.jpg http://s.csssr.ru/UE886ASBY/20181215_18.08.48.jpg. В макете есть http://s.csssr.ru/UE886ASBY/20181215_18.09.25.jpg http://s.csssr.ru/UE886ASBY/20181215_18.09.50.jpg http://s.csssr.ru/UE886ASBY/20181215_18.11.09.jpg

**Comment by TheHatSky** [comment]
Делаем.
