### ISSUE TITLE
Trigger default - неправильный цвет и вид шрифта

### ISSUE THREAD

**Issue by juliyalozovaya** [mindbox-moscow/ui-kit#69]
http://mindbox.csssr.ru/Main/ Блок Кому, текст "Настройте потребителей, к которым будут применяться действия триггера". Блок Что, текст "Настройте одно или несколько действий триггера". ФР: шрифт чёрный, обычный http://s.csssr.ru/UE886ASBY/20181214_15.51.10.jpg. ОР: Должен быть курсив #a12e1e, как в макете http://s.csssr.ru/UE886ASBY/20181214_15.52.00.jpg

**Comment by TheHatSky** [comment]
Пользы для проекта нет -- не делаем.
