### ISSUE TITLE
Вёрстка графика

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#697]
Основная большая задача: #695 

Снимаем риски: график можно сделать таким, чтобы нам подходил, кастомизовать как нам надо

- [x] Встраиваем компонент с графиком на страницу. Хотим использовать https://nivo.rocks/bar/ . Встраиваем с фейковыми данными, просто чтобы посмотреть, что оно работает. Напрямую на странице рассылок не используем компоненты из nivo.rocks, оборачиваем своим компонентом `BarChart`. Все необходимые пропсы нужно будет прокидывать через него.
- [x] Добавляем контроллы управления графиком: тип графика, выбор варианта, выбор периода, их стейт пока храним просто в стейте компонента.
- [x]  Правим стилистику графика: он должен выглядеть как на мокапах.
 - Используем не stacked bar, используем [кастомный Bar-компонент](https://nivo.rocks/storybook/?path=/story/bar--custom-bar-item).
 - По ховеру выделяем столбец более жирными цветами, рисуем пунктирную линию вокруг
 - Отображаем корректные подписи для данных по колонкам: умеем отображать даты по месяцам, по дням и по неделям.
 - По ховеру на наш кастомный компонент показываем тултип. Можно написать свой компонент для этого, но я нашёл [вот такой npm пакет](https://www.npmjs.com/package/react-svg-tooltip), может он подойдёт. Этот тултип должен принимать весь контент через детей и следовать за мышкой.

**Comment by vlad-pokusa** [comment]
Нужно закрыть график фичой MailingViewChart. Страницу скоро выкатим клиентам, надо чтобы то что в работе не было видно.

**Comment by vlad-pokusa** [comment]
- Графика не должно быть в ручных рассылках
- Должна быть подложка под графиком как в Фигме
- Месяцы при отображении на маке не должны отображаться так
<img width="1286" alt="Снимок экрана 2020-03-04 в 19 42 15" src="https://user-images.githubusercontent.com/57757197/75901961-5da96a80-5e50-11ea-97dc-7db0896865c0.png">
- Месяцы не должны иногда отображаться текстом белого цвета (или нужно понять, зачем это нужно)
- Округляем значения на столбцах графика до единиц (без десятых и сотых)
- По ховеру выделяем столбец более жирными цветами, рисуем пунктирную линию вокруг
- Отображаем корректные подписи для данных по колонкам: умеем отображать даты по месяцам, по дням и по неделям.
