### ISSUE TITLE
Trigger by event filled - Кнопка Условия фильтрации. Фон, шрифт и подчёркивание

### ISSUE THREAD

**Issue by juliyalozovaya** [mindbox-moscow/ui-kit#70]
http://mindbox.csssr.ru/MainActive/ 1. Фон #e2eaf0 http://s.csssr.ru/UE886ASBY/20181214_16.32.15.jpg. В макете #f2f2f2 http://s.csssr.ru/UE886ASBY/20181214_16.33.50.jpg. 2. Шрифт 12рх. В макете 14рх http://s.csssr.ru/UE886ASBY/20181214_16.34.51.jpg. 3. Текст на кнопке подчёркнут. В макете не подчёркнут

**Comment by TheHatSky** [comment]
Дубликат #53 (п. 3)
