### ISSUE TITLE
What - Set actions. Иконка лупа вместо календаря

### ISSUE THREAD

**Issue by juliyalozovaya** [mindbox-moscow/ui-kit#71]
http://mindbox.csssr.ru/What/ В блоках 2, 3, 4 в полях с датой иконка лупа http://s.csssr.ru/UE886ASBY/20181214_17.30.27.jpg. В макете - календарь http://s.csssr.ru/UE886ASBY/20181214_17.31.25.jpg

**Comment by TheHatSky** [comment]
Дубликат #75
