### ISSUE TITLE
Меню фильтра внутри рассылки никуда не влезает 

### ISSUE THREAD

**Issue by Shabanovv** [mindbox-moscow/ui-kit#714]
![image](https://user-images.githubusercontent.com/41429186/73083295-fb1d9000-3edb-11ea-9229-08aacc808598.png)

**Comment by stug111** [comment]
Это должно быть решено в этой задаче 
https://github.com/mindbox-moscow/ui-kit/issues/700

**Comment by Shabanovv** [comment]
https://github.com/mindbox-moscow/ui-kit/issues/700
