### ISSUE TITLE
When - Set actions. Цвет чекбокса

### ISSUE THREAD

**Issue by juliyalozovaya** [mindbox-moscow/ui-kit#73]
http://mindbox.csssr.ru/When/ Блок 2, 6, 7. Активный чекбокс "Триггер активен...". В реализации серый с чёрной галкой http://s.csssr.ru/UE886ASBY/20181215_17.57.59.jpg http://s.csssr.ru/UE886ASBY/20181215_19.02.29.jpg. В макете синий с белой галкой http://s.csssr.ru/UE886ASBY/20181215_17.59.21.jpg http://s.csssr.ru/UE886ASBY/20181215_19.01.10.jpg. Неактивный чекбокс серый http://s.csssr.ru/UE886ASBY/20181215_19.04.52.jpg. В макете белый http://s.csssr.ru/UE886ASBY/20181215_19.06.00.jpg

**Comment by TheHatSky** [comment]
Делать не нужно -- уже обсуждали.

В проекте везде используем стандартные системные чекбоксы.
Дизайнер работает на маке в сафари, поэтому у него они синие.
