### ISSUE TITLE
У кнопки добавить фильтр торчит лишний брекет

### ISSUE THREAD

**Issue by Shabanovv** [mindbox-moscow/ui-kit#744]
![image](https://user-images.githubusercontent.com/41429186/73838514-e7035800-4824-11ea-939e-b87bc8f42283.png)

Воспроизводится только на компе одного из сотрудников. Mac + chrome

Тред https://mindbox.slack.com/archives/CM9G5MY0M/p1580127055071600

**Comment by stug111** [comment]
Больше не воспроизводиться 
https://mindbox.slack.com/archives/CM9G5MY0M/p1580127055071600
