### ISSUE TITLE
When - Set actions. Иконка лупа вместо календаря

### ISSUE THREAD

**Issue by juliyalozovaya** [mindbox-moscow/ui-kit#75]
http://mindbox.csssr.ru/When/ Блок 2. В поле с датой иконка лупа http://s.csssr.ru/UE886ASBY/20181215_18.01.10.jpg. В макете календарь http://s.csssr.ru/UE886ASBY/20181215_17.53.54.jpg

**Comment by TheHatSky** [comment]
Нужно поправить, делаем.
