### ISSUE TITLE
Доработка фильтра по датам

### ISSUE THREAD

**Issue by vlad-pokusa** [mindbox-moscow/ui-kit#772]
- Выпилить из интерфейса задание точного времени, оставить даты
- При выборе "За все время" затирать даты в контроле задания дат, при выборе кнопок с периодами, выбранный дейтрендж отображается в контроле

**Comment by igorFrontend** [comment]
https://github.com/mindbox-moscow/ui-kit/pull/776

**Comment by vlad-pokusa** [comment]
>при выборе кнопок с периодами, выбранный дейтрендж отображается в контроле

Неделя = 7 дней (в контроле показываем дату 1го и 7го дня)
Месяц = 30 дней (в контроле показываем дату 1го и 307го дня)
Год = 365 дней

**Comment by vlad-pokusa** [comment]
<img width="983" alt="Снимок экрана 2020-02-19 в 13 21 51" src="https://user-images.githubusercontent.com/57757197/74837112-ce6d6480-5331-11ea-88f0-2bf63a0710a4.png">
Договорились не затирать даты, а заменять их серым текстом дд.мм.гггг как на мокапе

**Comment by buzorin** [comment]
Смотреть можно тут https://mindbox-moscow.github.io/ui-kit/#daterange
