### ISSUE TITLE
Прелоадер при обновлении данных для таблицы

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#775]
- При изменении ренджа дат делать таблицу прозрачной + прелоадер
- Контрол DateRange должен быть только в триггерных рассылках, в ручных - нет.

**Comment by vlad-pokusa** [comment]
Обсудили, что у нас данные по колонке "Целевое действие" (сделано отдельным запросом), могут грузиться очень долго, и их мы не ускорим в ближайшее время. 

Для рассылок с целевым действием должно работать так:
- Изменили рендж дат
- Таблица стала прозрачной
- Подгрузились основные данные и данные по доходности
- Таблица стала непрозрачной, прелоадер на месте целевого действия (сейчас там при смене ренджа вообще нет прелоадера, а просто старые данные)
- Дождались целевого действия и вывели его

**Comment by vlad-pokusa** [comment]
Обсудили, что должно работать так:

- Если нет никаких данных, таблица прозрачная, показывает старые данные, если какие-то находились в процессе получения - показываем прочерки (не крутящиеся в фоне прелоадеры)
- Если приехали какие-то данные, показываем их, а те что не приехали - прелоадеры
