### ISSUE TITLE
Второй этап: учимся отображать один вид графика с одним режимом группировки

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#787]
- [ ] Интегрируемся с бэком

При загрузке страницы запрашиваем сервис за данными для графика. Контракт сервиса должен быть понятен [из этой задачи](https://github.com/mindbox-moscow/ui-kit/issues/693). Нужно использовать следующую структуру стейта: 

```typescript
interface MailingReport {
    dataPerPeriod: MailingReportForPeriodData[];
}

interface MailingReportForPeriodData {
    period: MailingReportPeriod;
    dataPerVariant: MailingReportDataPerVariant[];
}

interface MailingReportPeriod {
    dateFrom: Date;
    dateTill: Date;
}

interface MailingReportDataPerVariant {
    variant: nubmer;
    data: MailingReportData;
}

interface MailingReportData {
    sentCount: number;
    deliveredCount: number;
    openedCount: number;
    clickedCount: number;
    unsubscribedCount: number;
    deliveredCount: number;
    conversionOrdersCount: number;
    attributedOrdersCount: nubmer;
    income: nubmer;
}
```

Сейчас запрашиваем с группировкой по дням, период берем из контролла периода, используемого для таблицы, тип данных используем пока запрашиваем `Common`.

- [ ] Отображаем данные графика `Отправлено/доставлено` для первого варианта

Логика графика: полная высота столбца -- количество отправок, то есть `sentCount`, высота синей части -- количество доставок, то есть `deliveredCount`.

[В документации](https://nivo.rocks/bar/) описано, что нужно передавать 3 пропса: 
 - `data` -- массив объектов данных. Из массива `MailingReport.dataPerPeriod` нужно map'ом собирать объект для графика. В нём должны быть все данные из `MailingReportData`, а так же текущий период.
- `indexBy` -- функа, возвращающая период
- `keys` -- массив названий свойств из объекта, по которым строится график. Мы не используем `stacked` график, хотя по-хорошему хотелось бы, так как нам нужно в UI работать со всем столбцом разом, в том числе и для тултипа. Эти риски будут сняты в первой части.
Соответственно, если мы едем со `stacked` графиком всё-таки, то нужно передавать `sentCount` и `deliveredCount`. Если едем с кастомным, то что передавать зависит от реализации кастома, но скорее всего только `sentCount` как наибольшее из этих двух значение.

- [ ] Дорабатываем тултип

Делаем тултип для этого типа графика: отправки и доставки у нас есть, период тоже нужно получать, плюс нужно вычислить процент доставок. Основной риск тут: не понятно, откуда взять период.

**Comment by vlad-pokusa** [comment]
- Должен быть 1 цвет + прозрачность (выбрали его на статусе)
- Тултип должен показывать реальные данные (сейчас он всегда одинаковый)
- График должен запрашивать реальные данные (сейчас везде одинаковые)
