### ISSUE TITLE
Третий этап: добавляем интерактива

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#788]
- [x] Поддерживаем переключение вариантов
В случае, если в рассылке 1 вариант, не показываем вообще выбор варианта. 
Отображаем корректно контролл выбора вариантов, если их несколько.
Используем выбранный в UI вариант, когда нам нужно получать данные для отчёта.
При выборе варианта "Все" суммируем данные по вариантам на фронте.

- [x] Перезапрашивать данные при изменении периода построения отчета

Точно так же, как мы сделали для таблицы, нужно сделать и для графика. Когда мы выбрали какой-то период в контролле над таблицей, нужно выполнить запрос на сервер за новыми данными для графика. Их нужно перезатирать полностью.

- [x] Перезапрашивать данные при изменении периода группировки

Точно так же нужно при изменении периода группировки полностью перезапрашивать данные с сервера. Тут же нужно научиться отображать график для различных периодов группировки: по дню, неделе, месяцу. Для каждого из этих периодов отличается способ представления периода на нижней оси. Это можно сделать через [кастомный компонент тиков](https://nivo.rocks/storybook/?path=/story/bar--custom-axis-ticks) через `renderTick`.

**Comment by vlad-pokusa** [comment]
На статусе был вопрос, что делать, если запрошен период "По неделям", а даты захватывают только половину недели - нужно показывать даты этой недели по оси Х, как есть по календарю, а данные для отображения брать за выбранный период (пол недели)

**Comment by vlad-pokusa** [comment]
- В режиме "По дням" всегда, при любом количестве столбцов, показываем день недели и ПОД ним число
- В сафаре график выглядит сломанным
<img width="1221" alt="Снимок экрана 2020-03-12 в 13 03 53" src="https://user-images.githubusercontent.com/57757197/76509999-f304ba00-6461-11ea-8f5b-1a6a98bfe442.png">

- В сафари при переключении на график "Конверсия в заказ" появляется вечный прелоадер, при этом если изменить промежуток дат, запрашиваются новые данные и отображаются но прелоадер не уходит. В консоли кажется ничего, в хроме не воспроизводится.
