### ISSUE TITLE
Четвертый этап: поддерживаем остальные типы отчетов

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#789]
У нас есть 5 типов отчета:
- Отправлено/доставлено (для которого мы уже написали логику)
- Процент открытий/Процент кликов
- Конверсия в заказ
- Динамика отписок
- Доход

Каждый из них может кастомизовать:
- Требуемый тип данных из сервиса для получения данных для этого отчета
- Форматтер значений для оси Y (там либо проценты, либо числа)
- Названия осей 
- Текст в тултипе
- Данные, по которым строится сам график: какие поля из `MailingReportData` использовать

- [x] Конфигурация для типов отчета

Делаем конфигурацию типов графиков (как `IMailingModelConfiguration`): `MailingReportTypeConfiguration` и соответственно `MailingReportType`. Сам `MailingReportType`  должен содержать все перечисленные выше параметры. 
Регистрируем в этой конфигурации тип отчета для `Отправлено/доставлено`, переписываем все места, которые закладывались, что это этот отчет, на использование конфигурации

- [x] Перезапрашивать данные при изменении типа отчета

Точно так же, как мы перезапрашиваем данные при изменении периода, нужно перезапрашивать их и при изменении типа отчета. Но нужно не перезаписывать данные целиком в этой ситуации, а просто дополнять. 
Важно, что не любое изменение типа отчета должно приводить к перезапросу данных, только в случае, если данных реально нехватает. Например, для отчетов `Отправлено/доставлено`, `Процент открытий/Процент кликов` и `Динамика отписок` данные приезжают из одного запроса с типом данных `Common`. Если тип запрашиваемых данных не поменялся, перезапрашивать их не нужно.

**Comment by vlad-pokusa** [comment]
/actions/mailing/34046/report - этот запрос получает данные для графиков по:

Отправлено/доставлено
Процент открытий/Процент кликов
Динамика отписок

/actions/mailing/34046/grouped-conversion-statistics  - этот запрос получает данные по количеству доставленных  и количеству заказов, нужен для графика по:

Конверсии в заказ (Кол-во заказов за период/Кол-во доставленных за период*100%) + Количество заказов в ховере

actions/mailing/34046/grouped-revenue-statistics  - этот запрос получает данные по выручке в динамике и количеству заказов, нужен для графика по:

Доходу (Доход на графике, выручка в ховере)

**Comment by vlad-pokusa** [comment]
Про кастомизацию:

> Требуемый тип данных из сервиса для получения данных для этого отчета 

Без Темы неясно, что он хотел сказать, сливаем этот пункт.

> Форматтер значений для оси Y (там либо проценты, либо числа)

График по Отправлено/доставлено - показываем по оси Y абсолютные значения (числа)
График по  Процент открытий/Процент кликов - показываем  по оси Y проценты
Конверсия в заказ - показываем  по оси Y проценты
Динамика отписок - показываем по оси Y проценты
Доход - показываем по оси Y числа

> Названия осей

В дизайне сейчас нет, но хочется чтобы была возможность в зависимости от выбора в дропдауне по-разному подписать оси

> Текст в тултипе

Есть мокапы того, что должно быть в тултипе для каждого типа графика. 
Там разные данные, разный текст и иногда разная структура.
 
<img width="468" alt="Снимок экрана 2020-02-25 в 20 31 41" src="https://user-images.githubusercontent.com/57757197/75271859-f1a28300-580d-11ea-8902-83727c369eed.png">


> Данные, по которым строится сам график: какие поля из MailingReportData использовать

В зависимости от выбранного графика/отчета в дропдауне использовать разные данные (итак уже можем?)

**Comment by vlad-pokusa** [comment]
@timramone насколько это актуально ввиду наших оптимизаций?

Важно, что не любое изменение типа отчета должно приводить к перезапросу данных, только в случае, если данных реально нехватает. Например, для отчетов Отправлено/доставлено, Процент открытий/Процент кликов и Динамика отписок данные приезжают из одного запроса с типом данных Common. Если тип запрашиваемых данных не поменялся, перезапрашивать их не нужно.

**Comment by igorFrontend** [comment]
> @timramone насколько это актуально ввиду наших оптимизаций?
> 
> Важно, что не любое изменение типа отчета должно приводить к перезапросу данных, только в случае, если данных реально нехватает. Например, для отчетов Отправлено/доставлено, Процент открытий/Процент кликов и Динамика отписок данные приезжают из одного запроса с типом данных Common. Если тип запрашиваемых данных не поменялся, перезапрашивать их не нужно.

такой оптимизации пока нет. Добавлю в 5 этапе
