### ISSUE TITLE
Пятый этап: красивости

### ISSUE THREAD

**Issue by buzorin** [mindbox-moscow/ui-kit#790]
- [x] Не даём разламывать график

При изменении периода построения отчета на такой, в котором более 60-ти дней запрещаем использовать период "по дням". Если он уже выбран, переключаем выбор на "за неделю". На это всё надо бы тесты написать.

**Comment by vlad-pokusa** [comment]
>При изменении периода построения отчета на такой, в котором более 60-ти дней запрещаем использовать период "по дням".

>При изменении периода построения отчета на такой, в котором более 419-ти дней запрещаем использовать период "по неделям".

Воркфлоу должен выглядеть так:

Клиент заходит в рассылку, там выбрано "Последние 7 дней" и "По дням"
Он выбирает 420 дней и жмет "построить"
Получает отчет за 420 дней + график за 420 дней с разбивкой по месяцам. Кнопки "По дням" и "по неделям" заблокированы.

**Comment by vlad-pokusa** [comment]
Буду смотреть тут:
- Переключалка периода разбиения не лочится, если выбрать "все время" а потом "7 дней"
- Ни при каком разбиении подписи осей не выезжают на график
- Выпилены пунктиры до оси Y
- Не мерцает ховер
- В ручных рассылках нет графика

**Comment by vlad-pokusa** [comment]
Фиксы которые хочется:

- Показываем радиобаттоны с вариантами независимо от наличия данных для конкретного варианта в конкретный период (если в рассылке 2+ вариантов, радиобаттоны на графике никогда не исчезают)
- Округление на графиках - на подписях и в ховерах нигде нет больше 2 знаков после запятой

<img width="309" alt="Снимок экрана 2020-03-24 в 14 22 38" src="https://user-images.githubusercontent.com/57757197/77530114-e9d40e00-6ea1-11ea-96b9-ae26d8cefdc9.png">

<img width="365" alt="Снимок экрана 2020-03-24 в 16 03 53" src="https://user-images.githubusercontent.com/57757197/77530148-f48ea300-6ea1-11ea-9f0f-5faf868e68e5.png">

<img width="1266" alt="Снимок экрана 2020-03-24 в 16 07 55" src="https://user-images.githubusercontent.com/57757197/77530193-02dcbf00-6ea2-11ea-9efc-4955b48820d4.png">

- Кнопки разбиения по периодам корректно работают в т.ч. в Сафари

**Comment by vlad-pokusa** [comment]
Радиобаттоны все также лочатся в сафари, "по неделям" заезжает на график
