### ISSUE TITLE
Tag: Хочу конфигурировать текст

### ISSUE THREAD

**Issue by shaykhullin** [mindbox-moscow/ui-kit#97]
### Что хочется сейчас
У контрола `Tag` хочется иметь а-ля `name`, так как он будет использоваться не только для триггеров

---

### О чем подумать
@TheHatSky Кажется, что нужен контрол а-ля `Badge`/`Notification`/`Panel`, вместо `Tag`. Проблема не в именовании, а в границах применения - нужна простая плашка, нужна плашка со временем. Нужно иметь возможность выбирать цвет, текст, либо объединить в режим

Сейчас решение получилось не очень универсальным для наших нужд

`Panel` нужен с возможностью выбора цвета без переопределения стилей в <style>, как сделано [тут](http://mindbox.csssr.ru/Whom/), текста, (размера??) . Без isDevelop и date. Одного форм-фактора - прямоугольник с одной секцией для текста. 

Для тега "вне режима девелопа" нужно более осознанное название. Вероятно, хотим сами управлять какой контрол рисовать: например `Badge` и `BadgeWithDateTime`. Так как для "боевого" нужно проставлять время запуска, на вызывающей стороне придется в любом случае писать if/?:/&&/... Режим разработки не единственный режим, который выбает у таких плашек - рассылка может быть в статусе отправляется, ошибка, алгоритм - не активен. На каждое состояние флаг иметь не хочется

У меня к UI-китам отношение такое, что каждый контрол должен быть максимально универсальным и не инкапсулирующий в себе несколько других, я вполне могу ошибаться

Примерный контракт такой:
```jsx
<SomePanel title/text/whatever="Заголовок"
    color={SomePanel.Colors.Green} // Purple, Gray, Blue и какие у нас еще в продукте используются
    key+ref+...=... />
```

**Comment by TheHatSky** [comment]
Да, ты прав, переделываем под более общий юз-кейс. Назвать `Badge`
