### ISSUE TITLE
Page: Хочу конфигурировать "кнопки сверху" 

### ISSUE THREAD

**Issue by shaykhullin** [mindbox-moscow/ui-kit#98]
###  Что хочется
У компонента Page нельзя конфигурировать кнопки, их название, расположение, клики по ним, иконки. Так же левый ряд кнопок местами колбасит и он не выравнивается по "размеру активной области страницы в ширину".

@TheHatSky Я слышал что этот компонент может быть выпилен из ui-kit'a, можно уточнить?

**Comment by TheHatSky** [comment]
Компонент `Page` не нужен в том виде, который есть сейчас. Нужно переделывать, либо удалить.

@shaykhullin с тебя продумать, на какие секции делится страница, без этого делать начинать не нужно.

**Comment by shaykhullin** [comment]
Пока неактуально
